# Generated by Django 3.0.7 on 2020-06-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200630_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourer',
            name='location',
            field=models.CharField(max_length=10),
        ),
    ]
