# Generated by Django 3.0.7 on 2020-06-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20200630_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourer',
            name='experience',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='labourer',
            name='wage',
            field=models.CharField(max_length=5),
        ),
    ]
