# Generated by Django 3.0.7 on 2020-07-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20200630_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=40)),
                ('wage', models.CharField(max_length=5)),
                ('experience', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Labourer',
        ),
    ]
