# Generated by Django 3.0.7 on 2020-07-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20200701_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='review',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
